# Generated by Django 5.2 on 2025-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topic_code_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_1',
            field=models.TextField(default='Default Option 1'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_2',
            field=models.TextField(default='Default Option 2'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_3',
            field=models.TextField(default='Default Option 3'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_4',
            field=models.TextField(default='Default Option 4'),
        ),
    ]
