# Generated by Django 5.2 on 2025-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
